name: Clang-Tidy

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches: [ master ]

jobs:
  cppcheck:
    name: Run Clang-Tidy
    runs-on: ubuntu-latest
    permissions:
      actions:         read
      contents:        read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake clang-tidy \
                                  pkg-config libcurl4-openssl-dev libuv1-dev \
                                  libgtest-dev nlohmann-json3-dev rapidjson-dev

      - name: Build
        run: |
          cmake -B       build/  -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          cmake --build  build/

      - name: Run Clang-Tidy on sources
        run: |
          cmake --build build/  --config Debug  --target clang-tidy
