name: Coverage

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches: [ master ]

jobs:
  ci:
    name: Build coverage
    runs-on: ubuntu-latest
    permissions:
      actions:         read
      contents:        read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake lcov \
                                  pkg-config libcurl4-openssl-dev libuv1-dev \
                                  libgtest-dev nlohmann-json3-dev
  
      - name: Build
        run: |
          cmake -B         build/  -DCMAKE_BUILD_TYPE=Debug
          cmake --build    build/
  
      - name: Test and coverage
        run: |
          ctest --test-dir build/ -T test -T coverage --output-on-failure
          lcov --capture --directory build/src/  --output-file build/coverage.info --ignore-errors gcov,gcov
          lcov --extract build/coverage.info '*/src/*' --output-file build/coverage.info.final
